version: '3.8'

services:
  service-a:
    image: service-a:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
    volumes:
      - ./data:/app/data
    networks:
      - app-network
    deploy:
      replicas: 1
  service-b:
    image: service-b:latest
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
    volumes:
      - ./data:/app/data
    networks:
      - app-network
    deploy:
      replicas: 1
networks:
  app-network:
    driver: overlay
    attachable: true